//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Kaynak kodu Microsoft.VSDesigner tarafından otomatik üretilmiş , Sürüm 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace okanorhancomAdmin.AdminWebServis {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://okanorhan.com/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback YeteneklerimCreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback YeteneklerimEditOperationCompleted;
        
        private System.Threading.SendOrPostCallback YeteneklerimDeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback YeteneklerimListOperationCompleted;
        
        private System.Threading.SendOrPostCallback KariyerCreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback KariyerEditOperationCompleted;
        
        private System.Threading.SendOrPostCallback KariyerDeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback KariyerListOperationCompleted;
        
        private System.Threading.SendOrPostCallback MakaleCreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback MakaleEditOperationCompleted;
        
        private System.Threading.SendOrPostCallback MakaleDeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback MakaleListOperationCompleted;
        
        private System.Threading.SendOrPostCallback YorumCreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback YorumEditOperationCompleted;
        
        private System.Threading.SendOrPostCallback YorumDeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback YorumListOperationCompleted;
        
        private System.Threading.SendOrPostCallback UyeCreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UyeEditOperationCompleted;
        
        private System.Threading.SendOrPostCallback UyeDeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback UyeListOperationCompleted;
        
        private System.Threading.SendOrPostCallback DosyaCreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback DosyaDeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback DosyaListOperationCompleted;
        
        private System.Threading.SendOrPostCallback MakaleYorumListOperationCompleted;
        
        private System.Threading.SendOrPostCallback MakaleYorumDetailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::okanorhancomAdmin.Properties.Settings.Default.okanorhancomAdmin_AdminWebServis_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event YeteneklerimCreateCompletedEventHandler YeteneklerimCreateCompleted;
        
        /// <remarks/>
        public event YeteneklerimEditCompletedEventHandler YeteneklerimEditCompleted;
        
        /// <remarks/>
        public event YeteneklerimDeleteCompletedEventHandler YeteneklerimDeleteCompleted;
        
        /// <remarks/>
        public event YeteneklerimListCompletedEventHandler YeteneklerimListCompleted;
        
        /// <remarks/>
        public event KariyerCreateCompletedEventHandler KariyerCreateCompleted;
        
        /// <remarks/>
        public event KariyerEditCompletedEventHandler KariyerEditCompleted;
        
        /// <remarks/>
        public event KariyerDeleteCompletedEventHandler KariyerDeleteCompleted;
        
        /// <remarks/>
        public event KariyerListCompletedEventHandler KariyerListCompleted;
        
        /// <remarks/>
        public event MakaleCreateCompletedEventHandler MakaleCreateCompleted;
        
        /// <remarks/>
        public event MakaleEditCompletedEventHandler MakaleEditCompleted;
        
        /// <remarks/>
        public event MakaleDeleteCompletedEventHandler MakaleDeleteCompleted;
        
        /// <remarks/>
        public event MakaleListCompletedEventHandler MakaleListCompleted;
        
        /// <remarks/>
        public event YorumCreateCompletedEventHandler YorumCreateCompleted;
        
        /// <remarks/>
        public event YorumEditCompletedEventHandler YorumEditCompleted;
        
        /// <remarks/>
        public event YorumDeleteCompletedEventHandler YorumDeleteCompleted;
        
        /// <remarks/>
        public event YorumListCompletedEventHandler YorumListCompleted;
        
        /// <remarks/>
        public event UyeCreateCompletedEventHandler UyeCreateCompleted;
        
        /// <remarks/>
        public event UyeEditCompletedEventHandler UyeEditCompleted;
        
        /// <remarks/>
        public event UyeDeleteCompletedEventHandler UyeDeleteCompleted;
        
        /// <remarks/>
        public event UyeListCompletedEventHandler UyeListCompleted;
        
        /// <remarks/>
        public event DosyaCreateCompletedEventHandler DosyaCreateCompleted;
        
        /// <remarks/>
        public event DosyaDeleteCompletedEventHandler DosyaDeleteCompleted;
        
        /// <remarks/>
        public event DosyaListCompletedEventHandler DosyaListCompleted;
        
        /// <remarks/>
        public event MakaleYorumListCompletedEventHandler MakaleYorumListCompleted;
        
        /// <remarks/>
        public event MakaleYorumDetailsCompletedEventHandler MakaleYorumDetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/YeteneklerimCreate", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool YeteneklerimCreate(string Yetenek, int YetenekYuzde, int Aktif) {
            object[] results = this.Invoke("YeteneklerimCreate", new object[] {
                        Yetenek,
                        YetenekYuzde,
                        Aktif});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void YeteneklerimCreateAsync(string Yetenek, int YetenekYuzde, int Aktif) {
            this.YeteneklerimCreateAsync(Yetenek, YetenekYuzde, Aktif, null);
        }
        
        /// <remarks/>
        public void YeteneklerimCreateAsync(string Yetenek, int YetenekYuzde, int Aktif, object userState) {
            if ((this.YeteneklerimCreateOperationCompleted == null)) {
                this.YeteneklerimCreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYeteneklerimCreateOperationCompleted);
            }
            this.InvokeAsync("YeteneklerimCreate", new object[] {
                        Yetenek,
                        YetenekYuzde,
                        Aktif}, this.YeteneklerimCreateOperationCompleted, userState);
        }
        
        private void OnYeteneklerimCreateOperationCompleted(object arg) {
            if ((this.YeteneklerimCreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YeteneklerimCreateCompleted(this, new YeteneklerimCreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/YeteneklerimEdit", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool YeteneklerimEdit(int YetenekID, string Yetenek, int YetenekYuzde, int Aktif) {
            object[] results = this.Invoke("YeteneklerimEdit", new object[] {
                        YetenekID,
                        Yetenek,
                        YetenekYuzde,
                        Aktif});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void YeteneklerimEditAsync(int YetenekID, string Yetenek, int YetenekYuzde, int Aktif) {
            this.YeteneklerimEditAsync(YetenekID, Yetenek, YetenekYuzde, Aktif, null);
        }
        
        /// <remarks/>
        public void YeteneklerimEditAsync(int YetenekID, string Yetenek, int YetenekYuzde, int Aktif, object userState) {
            if ((this.YeteneklerimEditOperationCompleted == null)) {
                this.YeteneklerimEditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYeteneklerimEditOperationCompleted);
            }
            this.InvokeAsync("YeteneklerimEdit", new object[] {
                        YetenekID,
                        Yetenek,
                        YetenekYuzde,
                        Aktif}, this.YeteneklerimEditOperationCompleted, userState);
        }
        
        private void OnYeteneklerimEditOperationCompleted(object arg) {
            if ((this.YeteneklerimEditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YeteneklerimEditCompleted(this, new YeteneklerimEditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/YeteneklerimDelete", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool YeteneklerimDelete(int YetenekID) {
            object[] results = this.Invoke("YeteneklerimDelete", new object[] {
                        YetenekID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void YeteneklerimDeleteAsync(int YetenekID) {
            this.YeteneklerimDeleteAsync(YetenekID, null);
        }
        
        /// <remarks/>
        public void YeteneklerimDeleteAsync(int YetenekID, object userState) {
            if ((this.YeteneklerimDeleteOperationCompleted == null)) {
                this.YeteneklerimDeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYeteneklerimDeleteOperationCompleted);
            }
            this.InvokeAsync("YeteneklerimDelete", new object[] {
                        YetenekID}, this.YeteneklerimDeleteOperationCompleted, userState);
        }
        
        private void OnYeteneklerimDeleteOperationCompleted(object arg) {
            if ((this.YeteneklerimDeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YeteneklerimDeleteCompleted(this, new YeteneklerimDeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/YeteneklerimList", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Yeteneklerim[] YeteneklerimList() {
            object[] results = this.Invoke("YeteneklerimList", new object[0]);
            return ((Yeteneklerim[])(results[0]));
        }
        
        /// <remarks/>
        public void YeteneklerimListAsync() {
            this.YeteneklerimListAsync(null);
        }
        
        /// <remarks/>
        public void YeteneklerimListAsync(object userState) {
            if ((this.YeteneklerimListOperationCompleted == null)) {
                this.YeteneklerimListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYeteneklerimListOperationCompleted);
            }
            this.InvokeAsync("YeteneklerimList", new object[0], this.YeteneklerimListOperationCompleted, userState);
        }
        
        private void OnYeteneklerimListOperationCompleted(object arg) {
            if ((this.YeteneklerimListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YeteneklerimListCompleted(this, new YeteneklerimListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/KariyerCreate", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool KariyerCreate(string IcerikTr, string IcereikEn, string BaslikTr, int Aktif) {
            object[] results = this.Invoke("KariyerCreate", new object[] {
                        IcerikTr,
                        IcereikEn,
                        BaslikTr,
                        Aktif});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void KariyerCreateAsync(string IcerikTr, string IcereikEn, string BaslikTr, int Aktif) {
            this.KariyerCreateAsync(IcerikTr, IcereikEn, BaslikTr, Aktif, null);
        }
        
        /// <remarks/>
        public void KariyerCreateAsync(string IcerikTr, string IcereikEn, string BaslikTr, int Aktif, object userState) {
            if ((this.KariyerCreateOperationCompleted == null)) {
                this.KariyerCreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKariyerCreateOperationCompleted);
            }
            this.InvokeAsync("KariyerCreate", new object[] {
                        IcerikTr,
                        IcereikEn,
                        BaslikTr,
                        Aktif}, this.KariyerCreateOperationCompleted, userState);
        }
        
        private void OnKariyerCreateOperationCompleted(object arg) {
            if ((this.KariyerCreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KariyerCreateCompleted(this, new KariyerCreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/KariyerEdit", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool KariyerEdit(int KariyerID, string IcerikTr, string IcerikEn, string BaslikTr, int Aktif) {
            object[] results = this.Invoke("KariyerEdit", new object[] {
                        KariyerID,
                        IcerikTr,
                        IcerikEn,
                        BaslikTr,
                        Aktif});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void KariyerEditAsync(int KariyerID, string IcerikTr, string IcerikEn, string BaslikTr, int Aktif) {
            this.KariyerEditAsync(KariyerID, IcerikTr, IcerikEn, BaslikTr, Aktif, null);
        }
        
        /// <remarks/>
        public void KariyerEditAsync(int KariyerID, string IcerikTr, string IcerikEn, string BaslikTr, int Aktif, object userState) {
            if ((this.KariyerEditOperationCompleted == null)) {
                this.KariyerEditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKariyerEditOperationCompleted);
            }
            this.InvokeAsync("KariyerEdit", new object[] {
                        KariyerID,
                        IcerikTr,
                        IcerikEn,
                        BaslikTr,
                        Aktif}, this.KariyerEditOperationCompleted, userState);
        }
        
        private void OnKariyerEditOperationCompleted(object arg) {
            if ((this.KariyerEditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KariyerEditCompleted(this, new KariyerEditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/KariyerDelete", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool KariyerDelete(int KariyerID) {
            object[] results = this.Invoke("KariyerDelete", new object[] {
                        KariyerID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void KariyerDeleteAsync(int KariyerID) {
            this.KariyerDeleteAsync(KariyerID, null);
        }
        
        /// <remarks/>
        public void KariyerDeleteAsync(int KariyerID, object userState) {
            if ((this.KariyerDeleteOperationCompleted == null)) {
                this.KariyerDeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKariyerDeleteOperationCompleted);
            }
            this.InvokeAsync("KariyerDelete", new object[] {
                        KariyerID}, this.KariyerDeleteOperationCompleted, userState);
        }
        
        private void OnKariyerDeleteOperationCompleted(object arg) {
            if ((this.KariyerDeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KariyerDeleteCompleted(this, new KariyerDeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/KariyerList", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Kariyer[] KariyerList() {
            object[] results = this.Invoke("KariyerList", new object[0]);
            return ((Kariyer[])(results[0]));
        }
        
        /// <remarks/>
        public void KariyerListAsync() {
            this.KariyerListAsync(null);
        }
        
        /// <remarks/>
        public void KariyerListAsync(object userState) {
            if ((this.KariyerListOperationCompleted == null)) {
                this.KariyerListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKariyerListOperationCompleted);
            }
            this.InvokeAsync("KariyerList", new object[0], this.KariyerListOperationCompleted, userState);
        }
        
        private void OnKariyerListOperationCompleted(object arg) {
            if ((this.KariyerListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KariyerListCompleted(this, new KariyerListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/MakaleCreate", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool MakaleCreate(string KisaIcerikTr, string KisaIcerikEn, string IcerikTr, string IcerikEn, string Image, int Aktif, int MakaleYayinSira, string RouteTr) {
            object[] results = this.Invoke("MakaleCreate", new object[] {
                        KisaIcerikTr,
                        KisaIcerikEn,
                        IcerikTr,
                        IcerikEn,
                        Image,
                        Aktif,
                        MakaleYayinSira,
                        RouteTr});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void MakaleCreateAsync(string KisaIcerikTr, string KisaIcerikEn, string IcerikTr, string IcerikEn, string Image, int Aktif, int MakaleYayinSira, string RouteTr) {
            this.MakaleCreateAsync(KisaIcerikTr, KisaIcerikEn, IcerikTr, IcerikEn, Image, Aktif, MakaleYayinSira, RouteTr, null);
        }
        
        /// <remarks/>
        public void MakaleCreateAsync(string KisaIcerikTr, string KisaIcerikEn, string IcerikTr, string IcerikEn, string Image, int Aktif, int MakaleYayinSira, string RouteTr, object userState) {
            if ((this.MakaleCreateOperationCompleted == null)) {
                this.MakaleCreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMakaleCreateOperationCompleted);
            }
            this.InvokeAsync("MakaleCreate", new object[] {
                        KisaIcerikTr,
                        KisaIcerikEn,
                        IcerikTr,
                        IcerikEn,
                        Image,
                        Aktif,
                        MakaleYayinSira,
                        RouteTr}, this.MakaleCreateOperationCompleted, userState);
        }
        
        private void OnMakaleCreateOperationCompleted(object arg) {
            if ((this.MakaleCreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MakaleCreateCompleted(this, new MakaleCreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/MakaleEdit", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool MakaleEdit(int MakaleID, string KisaIcerikTr, string KisaIcerikEn, string IcerikTr, string IcerikEn, string Image, int Aktif, int MakaleYayinSira, string RouteTr) {
            object[] results = this.Invoke("MakaleEdit", new object[] {
                        MakaleID,
                        KisaIcerikTr,
                        KisaIcerikEn,
                        IcerikTr,
                        IcerikEn,
                        Image,
                        Aktif,
                        MakaleYayinSira,
                        RouteTr});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void MakaleEditAsync(int MakaleID, string KisaIcerikTr, string KisaIcerikEn, string IcerikTr, string IcerikEn, string Image, int Aktif, int MakaleYayinSira, string RouteTr) {
            this.MakaleEditAsync(MakaleID, KisaIcerikTr, KisaIcerikEn, IcerikTr, IcerikEn, Image, Aktif, MakaleYayinSira, RouteTr, null);
        }
        
        /// <remarks/>
        public void MakaleEditAsync(int MakaleID, string KisaIcerikTr, string KisaIcerikEn, string IcerikTr, string IcerikEn, string Image, int Aktif, int MakaleYayinSira, string RouteTr, object userState) {
            if ((this.MakaleEditOperationCompleted == null)) {
                this.MakaleEditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMakaleEditOperationCompleted);
            }
            this.InvokeAsync("MakaleEdit", new object[] {
                        MakaleID,
                        KisaIcerikTr,
                        KisaIcerikEn,
                        IcerikTr,
                        IcerikEn,
                        Image,
                        Aktif,
                        MakaleYayinSira,
                        RouteTr}, this.MakaleEditOperationCompleted, userState);
        }
        
        private void OnMakaleEditOperationCompleted(object arg) {
            if ((this.MakaleEditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MakaleEditCompleted(this, new MakaleEditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/MakaleDelete", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool MakaleDelete(int MakaleID) {
            object[] results = this.Invoke("MakaleDelete", new object[] {
                        MakaleID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void MakaleDeleteAsync(int MakaleID) {
            this.MakaleDeleteAsync(MakaleID, null);
        }
        
        /// <remarks/>
        public void MakaleDeleteAsync(int MakaleID, object userState) {
            if ((this.MakaleDeleteOperationCompleted == null)) {
                this.MakaleDeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMakaleDeleteOperationCompleted);
            }
            this.InvokeAsync("MakaleDelete", new object[] {
                        MakaleID}, this.MakaleDeleteOperationCompleted, userState);
        }
        
        private void OnMakaleDeleteOperationCompleted(object arg) {
            if ((this.MakaleDeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MakaleDeleteCompleted(this, new MakaleDeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/MakaleList", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Makale[] MakaleList() {
            object[] results = this.Invoke("MakaleList", new object[0]);
            return ((Makale[])(results[0]));
        }
        
        /// <remarks/>
        public void MakaleListAsync() {
            this.MakaleListAsync(null);
        }
        
        /// <remarks/>
        public void MakaleListAsync(object userState) {
            if ((this.MakaleListOperationCompleted == null)) {
                this.MakaleListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMakaleListOperationCompleted);
            }
            this.InvokeAsync("MakaleList", new object[0], this.MakaleListOperationCompleted, userState);
        }
        
        private void OnMakaleListOperationCompleted(object arg) {
            if ((this.MakaleListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MakaleListCompleted(this, new MakaleListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/YorumCreate", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool YorumCreate(int MakaleID, string Baslik, string Yorum, int Aktif) {
            object[] results = this.Invoke("YorumCreate", new object[] {
                        MakaleID,
                        Baslik,
                        Yorum,
                        Aktif});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void YorumCreateAsync(int MakaleID, string Baslik, string Yorum, int Aktif) {
            this.YorumCreateAsync(MakaleID, Baslik, Yorum, Aktif, null);
        }
        
        /// <remarks/>
        public void YorumCreateAsync(int MakaleID, string Baslik, string Yorum, int Aktif, object userState) {
            if ((this.YorumCreateOperationCompleted == null)) {
                this.YorumCreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYorumCreateOperationCompleted);
            }
            this.InvokeAsync("YorumCreate", new object[] {
                        MakaleID,
                        Baslik,
                        Yorum,
                        Aktif}, this.YorumCreateOperationCompleted, userState);
        }
        
        private void OnYorumCreateOperationCompleted(object arg) {
            if ((this.YorumCreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YorumCreateCompleted(this, new YorumCreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/YorumEdit", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool YorumEdit(int MakaleID, int YorumID, string Baslik, string Yorum, int Aktif) {
            object[] results = this.Invoke("YorumEdit", new object[] {
                        MakaleID,
                        YorumID,
                        Baslik,
                        Yorum,
                        Aktif});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void YorumEditAsync(int MakaleID, int YorumID, string Baslik, string Yorum, int Aktif) {
            this.YorumEditAsync(MakaleID, YorumID, Baslik, Yorum, Aktif, null);
        }
        
        /// <remarks/>
        public void YorumEditAsync(int MakaleID, int YorumID, string Baslik, string Yorum, int Aktif, object userState) {
            if ((this.YorumEditOperationCompleted == null)) {
                this.YorumEditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYorumEditOperationCompleted);
            }
            this.InvokeAsync("YorumEdit", new object[] {
                        MakaleID,
                        YorumID,
                        Baslik,
                        Yorum,
                        Aktif}, this.YorumEditOperationCompleted, userState);
        }
        
        private void OnYorumEditOperationCompleted(object arg) {
            if ((this.YorumEditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YorumEditCompleted(this, new YorumEditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/YorumDelete", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool YorumDelete(int YorumID) {
            object[] results = this.Invoke("YorumDelete", new object[] {
                        YorumID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void YorumDeleteAsync(int YorumID) {
            this.YorumDeleteAsync(YorumID, null);
        }
        
        /// <remarks/>
        public void YorumDeleteAsync(int YorumID, object userState) {
            if ((this.YorumDeleteOperationCompleted == null)) {
                this.YorumDeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYorumDeleteOperationCompleted);
            }
            this.InvokeAsync("YorumDelete", new object[] {
                        YorumID}, this.YorumDeleteOperationCompleted, userState);
        }
        
        private void OnYorumDeleteOperationCompleted(object arg) {
            if ((this.YorumDeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YorumDeleteCompleted(this, new YorumDeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/YorumList", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Yorumlar[] YorumList() {
            object[] results = this.Invoke("YorumList", new object[0]);
            return ((Yorumlar[])(results[0]));
        }
        
        /// <remarks/>
        public void YorumListAsync() {
            this.YorumListAsync(null);
        }
        
        /// <remarks/>
        public void YorumListAsync(object userState) {
            if ((this.YorumListOperationCompleted == null)) {
                this.YorumListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYorumListOperationCompleted);
            }
            this.InvokeAsync("YorumList", new object[0], this.YorumListOperationCompleted, userState);
        }
        
        private void OnYorumListOperationCompleted(object arg) {
            if ((this.YorumListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YorumListCompleted(this, new YorumListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/UyeCreate", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UyeCreate(string KullaniciAdi, string Sifre, int Yetki, string Ad, string Soyad, string Email, int Aktif, string Image, string Yas, string Adres, string Telefon) {
            object[] results = this.Invoke("UyeCreate", new object[] {
                        KullaniciAdi,
                        Sifre,
                        Yetki,
                        Ad,
                        Soyad,
                        Email,
                        Aktif,
                        Image,
                        Yas,
                        Adres,
                        Telefon});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UyeCreateAsync(string KullaniciAdi, string Sifre, int Yetki, string Ad, string Soyad, string Email, int Aktif, string Image, string Yas, string Adres, string Telefon) {
            this.UyeCreateAsync(KullaniciAdi, Sifre, Yetki, Ad, Soyad, Email, Aktif, Image, Yas, Adres, Telefon, null);
        }
        
        /// <remarks/>
        public void UyeCreateAsync(string KullaniciAdi, string Sifre, int Yetki, string Ad, string Soyad, string Email, int Aktif, string Image, string Yas, string Adres, string Telefon, object userState) {
            if ((this.UyeCreateOperationCompleted == null)) {
                this.UyeCreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUyeCreateOperationCompleted);
            }
            this.InvokeAsync("UyeCreate", new object[] {
                        KullaniciAdi,
                        Sifre,
                        Yetki,
                        Ad,
                        Soyad,
                        Email,
                        Aktif,
                        Image,
                        Yas,
                        Adres,
                        Telefon}, this.UyeCreateOperationCompleted, userState);
        }
        
        private void OnUyeCreateOperationCompleted(object arg) {
            if ((this.UyeCreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UyeCreateCompleted(this, new UyeCreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/UyeEdit", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UyeEdit(string KullaniciAdi, string Sifre, int Yetki, string Ad, string Soyad, string Email, int Aktif, int KayitID, string Yas, string Adres, string Telefon) {
            object[] results = this.Invoke("UyeEdit", new object[] {
                        KullaniciAdi,
                        Sifre,
                        Yetki,
                        Ad,
                        Soyad,
                        Email,
                        Aktif,
                        KayitID,
                        Yas,
                        Adres,
                        Telefon});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UyeEditAsync(string KullaniciAdi, string Sifre, int Yetki, string Ad, string Soyad, string Email, int Aktif, int KayitID, string Yas, string Adres, string Telefon) {
            this.UyeEditAsync(KullaniciAdi, Sifre, Yetki, Ad, Soyad, Email, Aktif, KayitID, Yas, Adres, Telefon, null);
        }
        
        /// <remarks/>
        public void UyeEditAsync(string KullaniciAdi, string Sifre, int Yetki, string Ad, string Soyad, string Email, int Aktif, int KayitID, string Yas, string Adres, string Telefon, object userState) {
            if ((this.UyeEditOperationCompleted == null)) {
                this.UyeEditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUyeEditOperationCompleted);
            }
            this.InvokeAsync("UyeEdit", new object[] {
                        KullaniciAdi,
                        Sifre,
                        Yetki,
                        Ad,
                        Soyad,
                        Email,
                        Aktif,
                        KayitID,
                        Yas,
                        Adres,
                        Telefon}, this.UyeEditOperationCompleted, userState);
        }
        
        private void OnUyeEditOperationCompleted(object arg) {
            if ((this.UyeEditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UyeEditCompleted(this, new UyeEditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/UyeDelete", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UyeDelete(int KayitID) {
            object[] results = this.Invoke("UyeDelete", new object[] {
                        KayitID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UyeDeleteAsync(int KayitID) {
            this.UyeDeleteAsync(KayitID, null);
        }
        
        /// <remarks/>
        public void UyeDeleteAsync(int KayitID, object userState) {
            if ((this.UyeDeleteOperationCompleted == null)) {
                this.UyeDeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUyeDeleteOperationCompleted);
            }
            this.InvokeAsync("UyeDelete", new object[] {
                        KayitID}, this.UyeDeleteOperationCompleted, userState);
        }
        
        private void OnUyeDeleteOperationCompleted(object arg) {
            if ((this.UyeDeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UyeDeleteCompleted(this, new UyeDeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/UyeList", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Uye[] UyeList() {
            object[] results = this.Invoke("UyeList", new object[0]);
            return ((Uye[])(results[0]));
        }
        
        /// <remarks/>
        public void UyeListAsync() {
            this.UyeListAsync(null);
        }
        
        /// <remarks/>
        public void UyeListAsync(object userState) {
            if ((this.UyeListOperationCompleted == null)) {
                this.UyeListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUyeListOperationCompleted);
            }
            this.InvokeAsync("UyeList", new object[0], this.UyeListOperationCompleted, userState);
        }
        
        private void OnUyeListOperationCompleted(object arg) {
            if ((this.UyeListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UyeListCompleted(this, new UyeListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/DosyaCreate", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DosyaCreate(string SavePath) {
            object[] results = this.Invoke("DosyaCreate", new object[] {
                        SavePath});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DosyaCreateAsync(string SavePath) {
            this.DosyaCreateAsync(SavePath, null);
        }
        
        /// <remarks/>
        public void DosyaCreateAsync(string SavePath, object userState) {
            if ((this.DosyaCreateOperationCompleted == null)) {
                this.DosyaCreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDosyaCreateOperationCompleted);
            }
            this.InvokeAsync("DosyaCreate", new object[] {
                        SavePath}, this.DosyaCreateOperationCompleted, userState);
        }
        
        private void OnDosyaCreateOperationCompleted(object arg) {
            if ((this.DosyaCreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DosyaCreateCompleted(this, new DosyaCreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/DosyaDelete", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DosyaDelete(int DosyaID) {
            object[] results = this.Invoke("DosyaDelete", new object[] {
                        DosyaID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DosyaDeleteAsync(int DosyaID) {
            this.DosyaDeleteAsync(DosyaID, null);
        }
        
        /// <remarks/>
        public void DosyaDeleteAsync(int DosyaID, object userState) {
            if ((this.DosyaDeleteOperationCompleted == null)) {
                this.DosyaDeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDosyaDeleteOperationCompleted);
            }
            this.InvokeAsync("DosyaDelete", new object[] {
                        DosyaID}, this.DosyaDeleteOperationCompleted, userState);
        }
        
        private void OnDosyaDeleteOperationCompleted(object arg) {
            if ((this.DosyaDeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DosyaDeleteCompleted(this, new DosyaDeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/DosyaList", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Dosyalar[] DosyaList() {
            object[] results = this.Invoke("DosyaList", new object[0]);
            return ((Dosyalar[])(results[0]));
        }
        
        /// <remarks/>
        public void DosyaListAsync() {
            this.DosyaListAsync(null);
        }
        
        /// <remarks/>
        public void DosyaListAsync(object userState) {
            if ((this.DosyaListOperationCompleted == null)) {
                this.DosyaListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDosyaListOperationCompleted);
            }
            this.InvokeAsync("DosyaList", new object[0], this.DosyaListOperationCompleted, userState);
        }
        
        private void OnDosyaListOperationCompleted(object arg) {
            if ((this.DosyaListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DosyaListCompleted(this, new DosyaListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/MakaleYorumList", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MakaleYorumView MakaleYorumList() {
            object[] results = this.Invoke("MakaleYorumList", new object[0]);
            return ((MakaleYorumView)(results[0]));
        }
        
        /// <remarks/>
        public void MakaleYorumListAsync() {
            this.MakaleYorumListAsync(null);
        }
        
        /// <remarks/>
        public void MakaleYorumListAsync(object userState) {
            if ((this.MakaleYorumListOperationCompleted == null)) {
                this.MakaleYorumListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMakaleYorumListOperationCompleted);
            }
            this.InvokeAsync("MakaleYorumList", new object[0], this.MakaleYorumListOperationCompleted, userState);
        }
        
        private void OnMakaleYorumListOperationCompleted(object arg) {
            if ((this.MakaleYorumListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MakaleYorumListCompleted(this, new MakaleYorumListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://okanorhan.com/MakaleYorumDetails", RequestNamespace="http://okanorhan.com/", ResponseNamespace="http://okanorhan.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Yorumlar[] MakaleYorumDetails(int MakaleID) {
            object[] results = this.Invoke("MakaleYorumDetails", new object[] {
                        MakaleID});
            return ((Yorumlar[])(results[0]));
        }
        
        /// <remarks/>
        public void MakaleYorumDetailsAsync(int MakaleID) {
            this.MakaleYorumDetailsAsync(MakaleID, null);
        }
        
        /// <remarks/>
        public void MakaleYorumDetailsAsync(int MakaleID, object userState) {
            if ((this.MakaleYorumDetailsOperationCompleted == null)) {
                this.MakaleYorumDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMakaleYorumDetailsOperationCompleted);
            }
            this.InvokeAsync("MakaleYorumDetails", new object[] {
                        MakaleID}, this.MakaleYorumDetailsOperationCompleted, userState);
        }
        
        private void OnMakaleYorumDetailsOperationCompleted(object arg) {
            if ((this.MakaleYorumDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MakaleYorumDetailsCompleted(this, new MakaleYorumDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://okanorhan.com/")]
    public partial class Yeteneklerim {
        
        private int yetenekIDField;
        
        private string yetenekField;
        
        private System.Nullable<int> yetenekYuzdeField;
        
        private System.Nullable<bool> aktifField;
        
        /// <remarks/>
        public int YetenekID {
            get {
                return this.yetenekIDField;
            }
            set {
                this.yetenekIDField = value;
            }
        }
        
        /// <remarks/>
        public string Yetenek {
            get {
                return this.yetenekField;
            }
            set {
                this.yetenekField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> YetenekYuzde {
            get {
                return this.yetenekYuzdeField;
            }
            set {
                this.yetenekYuzdeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Aktif {
            get {
                return this.aktifField;
            }
            set {
                this.aktifField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://okanorhan.com/")]
    public partial class MakaleYorumView {
        
        private Makale[] makaleViewField;
        
        private Yorumlar[] yorumViewField;
        
        /// <remarks/>
        public Makale[] MakaleView {
            get {
                return this.makaleViewField;
            }
            set {
                this.makaleViewField = value;
            }
        }
        
        /// <remarks/>
        public Yorumlar[] YorumView {
            get {
                return this.yorumViewField;
            }
            set {
                this.yorumViewField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://okanorhan.com/")]
    public partial class Makale {
        
        private int makaleIDField;
        
        private string kisaIcerikTrField;
        
        private string kisaIcerikEnField;
        
        private string icerikTrField;
        
        private string icerikEnField;
        
        private string imageField;
        
        private System.Nullable<System.DateTime> tarihField;
        
        private System.Nullable<bool> aktifField;
        
        private System.Nullable<int> makaleYayinSiraField;
        
        private string routeTrField;
        
        private string routeEnField;
        
        /// <remarks/>
        public int MakaleID {
            get {
                return this.makaleIDField;
            }
            set {
                this.makaleIDField = value;
            }
        }
        
        /// <remarks/>
        public string KisaIcerikTr {
            get {
                return this.kisaIcerikTrField;
            }
            set {
                this.kisaIcerikTrField = value;
            }
        }
        
        /// <remarks/>
        public string KisaIcerikEn {
            get {
                return this.kisaIcerikEnField;
            }
            set {
                this.kisaIcerikEnField = value;
            }
        }
        
        /// <remarks/>
        public string IcerikTr {
            get {
                return this.icerikTrField;
            }
            set {
                this.icerikTrField = value;
            }
        }
        
        /// <remarks/>
        public string IcerikEn {
            get {
                return this.icerikEnField;
            }
            set {
                this.icerikEnField = value;
            }
        }
        
        /// <remarks/>
        public string Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Tarih {
            get {
                return this.tarihField;
            }
            set {
                this.tarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Aktif {
            get {
                return this.aktifField;
            }
            set {
                this.aktifField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> MakaleYayinSira {
            get {
                return this.makaleYayinSiraField;
            }
            set {
                this.makaleYayinSiraField = value;
            }
        }
        
        /// <remarks/>
        public string RouteTr {
            get {
                return this.routeTrField;
            }
            set {
                this.routeTrField = value;
            }
        }
        
        /// <remarks/>
        public string RouteEn {
            get {
                return this.routeEnField;
            }
            set {
                this.routeEnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://okanorhan.com/")]
    public partial class Yorumlar {
        
        private int yorumIDField;
        
        private System.Nullable<System.DateTime> tarihField;
        
        private string baslikField;
        
        private string yorumField;
        
        private System.Nullable<int> makaleIDField;
        
        private System.Nullable<bool> aktifField;
        
        /// <remarks/>
        public int YorumID {
            get {
                return this.yorumIDField;
            }
            set {
                this.yorumIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Tarih {
            get {
                return this.tarihField;
            }
            set {
                this.tarihField = value;
            }
        }
        
        /// <remarks/>
        public string Baslik {
            get {
                return this.baslikField;
            }
            set {
                this.baslikField = value;
            }
        }
        
        /// <remarks/>
        public string Yorum {
            get {
                return this.yorumField;
            }
            set {
                this.yorumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> MakaleID {
            get {
                return this.makaleIDField;
            }
            set {
                this.makaleIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Aktif {
            get {
                return this.aktifField;
            }
            set {
                this.aktifField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://okanorhan.com/")]
    public partial class Dosyalar {
        
        private int dosyaIDField;
        
        private string dosyaPathField;
        
        /// <remarks/>
        public int DosyaID {
            get {
                return this.dosyaIDField;
            }
            set {
                this.dosyaIDField = value;
            }
        }
        
        /// <remarks/>
        public string DosyaPath {
            get {
                return this.dosyaPathField;
            }
            set {
                this.dosyaPathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://okanorhan.com/")]
    public partial class Uye {
        
        private int kayitIDField;
        
        private string kullaniciAdiField;
        
        private string sifreField;
        
        private System.Nullable<int> yetkiField;
        
        private string adField;
        
        private string soyadField;
        
        private string emailField;
        
        private System.Nullable<bool> aktifField;
        
        private string imageField;
        
        private string yasField;
        
        private string adresField;
        
        private string telefonField;
        
        /// <remarks/>
        public int KayitID {
            get {
                return this.kayitIDField;
            }
            set {
                this.kayitIDField = value;
            }
        }
        
        /// <remarks/>
        public string KullaniciAdi {
            get {
                return this.kullaniciAdiField;
            }
            set {
                this.kullaniciAdiField = value;
            }
        }
        
        /// <remarks/>
        public string Sifre {
            get {
                return this.sifreField;
            }
            set {
                this.sifreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Yetki {
            get {
                return this.yetkiField;
            }
            set {
                this.yetkiField = value;
            }
        }
        
        /// <remarks/>
        public string Ad {
            get {
                return this.adField;
            }
            set {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        public string Soyad {
            get {
                return this.soyadField;
            }
            set {
                this.soyadField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Aktif {
            get {
                return this.aktifField;
            }
            set {
                this.aktifField = value;
            }
        }
        
        /// <remarks/>
        public string Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        public string Yas {
            get {
                return this.yasField;
            }
            set {
                this.yasField = value;
            }
        }
        
        /// <remarks/>
        public string Adres {
            get {
                return this.adresField;
            }
            set {
                this.adresField = value;
            }
        }
        
        /// <remarks/>
        public string Telefon {
            get {
                return this.telefonField;
            }
            set {
                this.telefonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://okanorhan.com/")]
    public partial class Kariyer {
        
        private int kariyerIDField;
        
        private string icerikTrField;
        
        private string icerikEnField;
        
        private string baslikTrField;
        
        private string baslikEnField;
        
        private System.Nullable<bool> aktifField;
        
        /// <remarks/>
        public int KariyerID {
            get {
                return this.kariyerIDField;
            }
            set {
                this.kariyerIDField = value;
            }
        }
        
        /// <remarks/>
        public string IcerikTr {
            get {
                return this.icerikTrField;
            }
            set {
                this.icerikTrField = value;
            }
        }
        
        /// <remarks/>
        public string IcerikEn {
            get {
                return this.icerikEnField;
            }
            set {
                this.icerikEnField = value;
            }
        }
        
        /// <remarks/>
        public string BaslikTr {
            get {
                return this.baslikTrField;
            }
            set {
                this.baslikTrField = value;
            }
        }
        
        /// <remarks/>
        public string BaslikEn {
            get {
                return this.baslikEnField;
            }
            set {
                this.baslikEnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Aktif {
            get {
                return this.aktifField;
            }
            set {
                this.aktifField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void YeteneklerimCreateCompletedEventHandler(object sender, YeteneklerimCreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YeteneklerimCreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YeteneklerimCreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void YeteneklerimEditCompletedEventHandler(object sender, YeteneklerimEditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YeteneklerimEditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YeteneklerimEditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void YeteneklerimDeleteCompletedEventHandler(object sender, YeteneklerimDeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YeteneklerimDeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YeteneklerimDeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void YeteneklerimListCompletedEventHandler(object sender, YeteneklerimListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YeteneklerimListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YeteneklerimListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Yeteneklerim[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Yeteneklerim[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void KariyerCreateCompletedEventHandler(object sender, KariyerCreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KariyerCreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KariyerCreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void KariyerEditCompletedEventHandler(object sender, KariyerEditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KariyerEditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KariyerEditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void KariyerDeleteCompletedEventHandler(object sender, KariyerDeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KariyerDeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KariyerDeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void KariyerListCompletedEventHandler(object sender, KariyerListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KariyerListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KariyerListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Kariyer[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Kariyer[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void MakaleCreateCompletedEventHandler(object sender, MakaleCreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MakaleCreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MakaleCreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void MakaleEditCompletedEventHandler(object sender, MakaleEditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MakaleEditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MakaleEditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void MakaleDeleteCompletedEventHandler(object sender, MakaleDeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MakaleDeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MakaleDeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void MakaleListCompletedEventHandler(object sender, MakaleListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MakaleListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MakaleListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Makale[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Makale[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void YorumCreateCompletedEventHandler(object sender, YorumCreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YorumCreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YorumCreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void YorumEditCompletedEventHandler(object sender, YorumEditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YorumEditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YorumEditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void YorumDeleteCompletedEventHandler(object sender, YorumDeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YorumDeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YorumDeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void YorumListCompletedEventHandler(object sender, YorumListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YorumListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YorumListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Yorumlar[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Yorumlar[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void UyeCreateCompletedEventHandler(object sender, UyeCreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UyeCreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UyeCreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void UyeEditCompletedEventHandler(object sender, UyeEditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UyeEditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UyeEditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void UyeDeleteCompletedEventHandler(object sender, UyeDeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UyeDeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UyeDeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void UyeListCompletedEventHandler(object sender, UyeListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UyeListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UyeListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Uye[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Uye[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DosyaCreateCompletedEventHandler(object sender, DosyaCreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DosyaCreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DosyaCreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DosyaDeleteCompletedEventHandler(object sender, DosyaDeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DosyaDeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DosyaDeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DosyaListCompletedEventHandler(object sender, DosyaListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DosyaListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DosyaListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Dosyalar[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Dosyalar[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void MakaleYorumListCompletedEventHandler(object sender, MakaleYorumListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MakaleYorumListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MakaleYorumListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MakaleYorumView Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MakaleYorumView)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void MakaleYorumDetailsCompletedEventHandler(object sender, MakaleYorumDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MakaleYorumDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MakaleYorumDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Yorumlar[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Yorumlar[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591