//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace okanorhancomWebServis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kariyer
    {
        public int KariyerID { get; set; }
        public string IcerikTr { get; set; }
        public string IcerikEn { get; set; }
        public string BaslikTr { get; set; }
        public string BaslikEn { get; set; }
        public Nullable<bool> Aktif { get; set; }
    }
}
