//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace okanorhancomWebServis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uye
    {
        public int KayitID { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public Nullable<int> Yetki { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public string Image { get; set; }
        public string Yas { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
    }
}
