//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace okanorhancomWebServis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        public int YorumID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Baslik { get; set; }
        public string Yorum { get; set; }
        public Nullable<int> MakaleID { get; set; }
        public Nullable<bool> Aktif { get; set; }
    }
}
